// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuyCoinsCard: typeof import('./components/buy-coins-card.vue')['default']
    DialogHeaderMore: typeof import('./components/dialog-header-more.vue')['default']
    DialogOauth: typeof import('./components/dialog-oauth.vue')['default']
    DialogSupportEmail: typeof import('./components/dialog-support-email.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    PageLogin: typeof import('./components/page-login.vue')['default']
    PageRecoveryGuardian: typeof import('./components/page-recovery-guardian.vue')['default']
    PageRecoveryGuardianVerify: typeof import('./components/page-recovery-guardian-verify.vue')['default']
    PageRecoveryPassword: typeof import('./components/page-recovery-password.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpButton: typeof import('./components/up-button.vue')['default']
    UpConfirm: typeof import('./components/up-confirm.vue')['default']
    UpDialog: typeof import('./components/up-dialog.vue')['default']
    UpDollar: typeof import('./components/up-dollar.vue')['default']
    UpFormItem: typeof import('./components/up-form-item.vue')['default']
    UpHeader: typeof import('./components/up-header.vue')['default']
    UpHeaderConnect: typeof import('./components/up-header-connect.vue')['default']
    UpIcon: typeof import('./components/up-icon.vue')['default']
    UpInput: typeof import('./components/up-input.vue')['default']
    UpNft: typeof import('./components/up-nft.vue')['default']
    UpSign: typeof import('./components/up-sign.vue')['default']
    UpSignCard: typeof import('./components/up-sign-card.vue')['default']
    UpSupportedBy: typeof import('./components/up-supported-by.vue')['default']
    UpToken: typeof import('./components/up-token.vue')['default']
  }
}

export {}
