// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogSupportEmail: typeof import('./components/dialog-support-email.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PageLogin: typeof import('./components/page-login.vue')['default']
    PageRecovery: typeof import('./components/page-recovery.vue')['default']
    PageRecoveryGuardian: typeof import('./components/page-recovery-guardian.vue')['default']
    PageRecoveryPassword: typeof import('./components/page-recovery-password.vue')['default']
    PageRegister: typeof import('./components/page-register.vue')['default']
    PageRegisterGuardians: typeof import('./components/page-register-guardians.vue')['default']
    PageVerify: typeof import('./components/page-verify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpBalance: typeof import('./components/up-balance.vue')['default']
    UpButton: typeof import('./components/up-button.vue')['default']
    UpHeader: typeof import('./components/up-header.vue')['default']
    UpIcon: typeof import('./components/up-icon.vue')['default']
  }
}

export {}
